# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2025      GSI Helmholtzzentrum fuer Schwerionenforschung GmbH
#                       Matthias Kretz <m.kretz@gsi.de>

objdir = obj

CXXFLAGS+=-std=c++26 -Wall -Wextra -Werror -O2 -g0 -Wno-attributes -D_GLIBCXX_ASSERTIONS=1 $(FLAGS)
CXXFLAGS_clang := -Wno-unknown-pragmas -ferror-limit=3
CXXFLAGS_gcc := -fconcepts-diagnostics-depth=3 -fconstexpr-ops-limit=67108864 -fmax-errors=3

cxx_version := $(shell $(CXX) --version | head -n1)

ifneq ($(findstring clang,$(cxx_version)),)
compiler:=clang
else ifneq ($(findstring g++,$(cxx_version))$(findstring GCC,$(cxx_version)),)
compiler:=gcc
else
compiler:=unknown
endif

ifeq ($(file < .cxx_version),)
$(file > .cxx_version,$(cxx_version))
else
ifneq ($(file < .cxx_version),$(cxx_version))
$(info Remove PCH because the compiler changed from "$(file < .cxx_version)" to "$(cxx_version)". $(shell rm -f $(objdir)/*.hpp.gch))
$(file > .cxx_version,$(cxx_version))
endif
endif

print_compiler_info:
	@echo "Compiler: $(CXX) $(ICECC_CXX)"
	@echo "          $(cxx_version)"
	@echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"

CXXFLAGS += $(CXXFLAGS_$(compiler))

#-D_GLIBCXX_DEBUG_UB=1

ifeq ($(ICECC_CXX),)
LINK_CXX := $(CXX)
else
LINK_CXX := $(ICECC_CXX)
endif

ifeq ($(notdir $(realpath $(CXX))),distcc)
# using distcc
ifeq ($(shell $(realpath $(CXX)) --show-hosts),)
# except, not really
DIRECT := 1
endif

else ifeq ($(notdir $(realpath $(CXX))),icecc)
# using icecc
ifeq ($(ICECC),no)
DIRECT := 1
else ifeq ($(ICECC),disable)
DIRECT := 1
else ifneq ($(DIRECT),)
ifneq ($(ICECC_CXX),)
# with icecream, DIRECT, and ICECC_CXX set, and CXX resolving to icecc, compile
# locally but allocate slots on the icecream scheduler
export ICECC=no
endif
endif

else
# CXX isn't using icecream or distcc
DIRECT := 1
endif

testarchs ::= athlon64 \
	     nocona \
	     core2 \
	     westmere \
	     ivybridge \
	     bdver4 \
	     skylake \
	     znver4 \
	     skylake-avx512

tests ::= $(patsubst tests/%.cpp,%,$(wildcard tests/*.cpp))

testtypes ::= signed-char \
	     unsigned-char \
	     signed-short \
	     unsigned-short \
	     signed-int \
	     unsigned-int \
	     signed-long-long \
	     unsigned-long-long \
	     float \
	     double

ifneq ($(compiler),clang)
testtypes += std::float16_t
endif

testtypes ::= $(subst ::,--,$(testtypes))

testwidths ::= $(shell seq 1 67)

getwidth = $(subst .,,$(suffix $(1)))
gettype = $(subst -, ,$(subst --,::,$(subst .,,$(basename $(notdir $(1))))))
getarch = $(subst .,,$(suffix $(subst /,,$(dir $(1)))))
gettest = $(basename $(subst /,,$(dir $(1))))

ifneq ($(MAKE_TERMOUT),)
CXXFLAGS += -fdiagnostics-color=always
msg_build := \e[34;1mBuild\e[0m
msg_link  := \e[33;1mLink \e[0m
msg_run   := \e[32;1mRun✔️ \e[0m
msg_runf  := \e[31;1mRun❌\e[0m
else
msg_build := Build:
msg_link  := Link :
msg_run   := Run :)
msg_runf  := Run :(
endif

diag_transform := sed -e 's/\(, \)\?std::__detail::__build_flags{[^,]*,[^}]*}//g' -e 's/\<std::datapar::/dp::/g' -e 's/\<std::__detail::/🙈/g'

define call_compiler
{ { $(CXX) $(1) 2>&1; echo $$?>&2; } | $(diag_transform); } 3>&2 2>&1 1>&3 | { read s; [ $$s -gt 0 ] && echo Build command was: $(CXX) $(1); exit $$s; }
endef

print_progress := true

$(objdir)/%.fast-math.hpp: $(objdir)/%.hpp
	@cp $< $@

define pch_template
$(objdir)/$(1).hpp: tests/unittest*.h tests/*.cpp | $(objdir)
	@echo "Generate $$@"
	@grep -h '^ *# *include ' tests/unittest*.h tests/*.cpp|grep -v unittest.h|sed 's,","$(PWD)/tests/,' > $$@

$(objdir)/$(1).depend: $(objdir)/$(1).hpp
	@echo "Update $(1) dependencies"
	@$$(CXX) $$(CXXFLAGS) -march=$(1) -MM -MT "$(objdir)/$(1).hpp" $(objdir)/$(1).hpp | sed 's, $(objdir)/$(1).hpp ,,' > $$@

include $(objdir)/$(1).depend

$(objdir)/$(1).hpp.gch: $(objdir)/$(1).hpp | print_compiler_info
	@printf -- '$$(msg_build) pre-compiled header for $(1)\n'
	@$$(call call_compiler, $$(CXXFLAGS) -march=$(1) -c $$< -o $$@)

$(objdir)/$(1).fast-math.hpp.gch: $(objdir)/$(1).fast-math.hpp | print_compiler_info
	@printf -- '$$(msg_build) pre-compiled fast-math header for $(1)\n'
	@$$(call call_compiler, $$(CXXFLAGS) -ffast-math -march=$(1) -c $$< -o $$@)

endef

$(foreach arch,$(testarchs),\
	$(eval $(call pch_template,$(arch))))

no_fast_math = $(shell head -n10 tests/$(1).cpp | grep -q no-fast-math && echo 1 || echo 0)

# arguments: test, arch
define exe_template
check/$(1).$(2)/%: tests/$(1).cpp $(objdir)/$(2).hpp.gch tests/unittest*.h
	@printf -- '$$(msg_build) $(if $(DIRECT),and link )$$(@:check/%=  $(objdir)/%.exe)\n'
	@mkdir -p $$(dir $$(@:check/%=$(objdir)/%.exe)) $$(dir $$@)
	@rm -f $$(@:check/%=$(objdir)/%.exe) $$@
	@$$(call call_compiler,$$(CXXFLAGS) -march=$(2) -D UNITTEST_TYPE="$$(call gettype,$$*)" -D UNITTEST_WIDTH=$$(call getwidth,$$*) -include $(objdir)/$(2).hpp $(if $(DIRECT),-o $$(@:check/%=$(objdir)/%.exe),-c -o $$(@:check/%=$(objdir)/%.o)) $$<)
ifeq ($(DIRECT),)
	@true || printf -- '$$(msg_link) $$@\n'
	@$$(LINK_CXX) $$(CXXFLAGS) -march=$(2) -o $$(@:check/%=$(objdir)/%.exe) $$(@:check/%=$(objdir)/%.o)
	@touch -r $$(@:check/%=$(objdir)/%.o) $$(@:check/%=$(objdir)/%.exe)
	@rm $$(@:check/%=$(objdir)/%.o)
endif
	@rm -f $$@.failed
	@$$(@:check/%=$(objdir)/%.exe) >$$@ 2>&1 && { \
		printf -- '$$(msg_run) %-60s %s\n' '$$@' "$$$$($$(print_progress))"; \
		touch -r $$(@:check/%=$(objdir)/%.exe) $$@; \
	} || { \
		printf -- '$$(msg_runf) $$@\n'; \
		cat $$@; \
		mv $$@ $$@.failed; \
		false; \
	}

check/fast-math/$(1).$(2)/%: tests/$(1).cpp $(objdir)/$(2).fast-math.hpp.gch tests/unittest*.h
ifeq ($(call no_fast_math,$(1)),1)
	@mkdir -p $$(dir $$@)
	@touch $$@
else
	@mkdir -p $$(dir $$(@:check/%=$(objdir)/%.exe)) $$(dir $$@)
	@printf -- '$$(msg_build) $(if $(DIRECT),and link )$$(@:check/%=  $(objdir)/%.exe)\n'
	@rm -f $$(@:check/%=$(objdir)/%.exe) $$@
	@$$(call call_compiler,$$(CXXFLAGS) -ffast-math -march=$(2) -D UNITTEST_TYPE="$$(call gettype,$$*)" -D UNITTEST_WIDTH=$$(call getwidth,$$*) -include $(objdir)/$(2).fast-math.hpp $(if $(DIRECT),-o $$(@:check/%=$(objdir)/%.exe),-c -o $$(@:check/%=$(objdir)/%.o)) $$<)
ifeq ($(DIRECT),)
	@true || printf -- '$$(msg_link) $$@\n'
	@$$(LINK_CXX) $$(CXXFLAGS) -ffast-math -march=$(2) -o $$(@:check/%=$(objdir)/%.exe) $$(@:check/%=$(objdir)/%.o)
	@touch -r $$(@:check/%=$(objdir)/%.o) $$(@:check/%=$(objdir)/%.exe)
	@rm $$(@:check/%=$(objdir)/%.o)
endif
	@rm -f $$@.failed
	@$$(@:check/%=$(objdir)/%.exe) >$$@ 2>&1 && { \
		printf -- '$$(msg_run) %-60s %s\n' '$$@' "$$$$($$(print_progress))"; \
		touch -r $$(@:check/%=$(objdir)/%.exe) $$@; \
	} || { \
		printf -- '$$(msg_runf) $$@\n'; \
		cat $$@; \
		mv $$@ $$@.failed; \
		false; \
	}
endif

endef

$(foreach arch,$(testarchs),\
	$(foreach t,$(tests),\
	$(eval $(call exe_template,$(t),$(arch)))))

constexpr_checks ::= $(foreach arch,$(testarchs),$(objdir)/constexpr.$(arch).s)

.PHONY: check-constexpr
check-constexpr: $(shell shuf -e -- $(constexpr_checks))

check_targets := $(objdir)/check.targets

codegen_files ::= $(wildcard codegen/*.c++)
codegen_names ::= $(patsubst codegen/%.c++,%,$(codegen_files))
codegen_targets ::= $(patsubst %,check-codegen-%,$(codegen_names))

ifneq ($(SIMD_OBJ_SUBST),)
ifneq ($(objdir),obj)
$(error Ambiguous instructions: both 'objdir' and 'SIMD_OBJ_SUBST' are set to non-default values)
endif
real_obj_dir=$(shell echo $$PWD|sed '$(SIMD_OBJ_SUBST)')
make_obj_dir_rule := mkdir -p $(real_obj_dir); ln -s $(real_obj_dir) $(objdir)
else
make_obj_dir_rule := mkdir -p $(objdir)
endif

$(objdir):
	@echo "Set up build dir and check dir"
	@$(make_obj_dir_rule)
	@mkdir -p $(objdir)/check
	@ln -s $(objdir)/check check

$(objdir)/codegen.depend: $(objdir) $(codegen_files)
	@echo "Update codegen dependencies ..."
	$(file >$@)
	$(foreach c,$(codegen_names),\
	  $(shell $(CXX) $(CXXFLAGS) -MM -MT $(objdir)/codegen.$c.s codegen/$c.c++ >> $@))

include $(objdir)/codegen.depend

$(objdir)/constexpr.%.s: $(objdir)/%.hpp.gch
	@printf -- '$(msg_build) constexpr tests for $*\n'
	@$(CXX) $(CXXFLAGS) -march=$* -include $(objdir)/$*.hpp -S -o $@ constexpr_tests.c++

.PHONY: always-remake
always-remake: ;

check-codegen-%: $(objdir)/codegen.%.s codegen/check.sh
	@echo "Testing for expected instructions in $<"
	@codegen/check.sh "codegen/$*.c++" "$<"

$(objdir)/codegen.%.s: codegen/%.c++ $(objdir)
	@echo "Building $@"
	@$(CXX) $(CXXFLAGS) -masm=intel -march=skylake -fcf-protection=none -S -o $@ $<
	@cat $@ | grep -v '^\s*\.' | c++filt > $@.tmp
	@mv $@.tmp $@

